import dayjs from "dayjs";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Calendar from "../components/Calendar";

export default function Home() {
  function onPanelChange(value, mode) {
    console.log(value, mode);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Antd Calendar Demo</h1>
        <div className={styles.siteCalendarDemoCard}>
          <Calendar
            validRange={[dayjs().add(0, "day"), dayjs().add(1, "year")]}
            fullscreen={false}
            onPanelChange={onPanelChange}
          />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
